### ISSUE TITLE
Fails for Windows OpenSSH deployment

### ISSUE THREAD

**Issue by RohanSakhale** [la-haute-societe/ssh-deploy-release#20]
## Bugs

1. Fails due to path formation uses Linux directory separator instead of Windows
2. Error occurred while processing: -p
     - `-p` switch in mkdir is not recognised in windows

**Comment by nstCactus** [comment]
We decided to focus on supporting deploying to Linux as this is the platform most hosting providers support and the one we're most familiar with. You should be able to use this to deploy to most UNIX systems though (including macOS) but this hasn't been tested.
I'll add a note on supported platforms in the README to make this clear.
