### ISSUE TITLE
tar gz archive type doesn't actually compress

### ISSUE THREAD

**Issue by jackc** [la-haute-societe/ssh-deploy-release#21]
From the readme:

```
#### options.archiveType
`zip` : Use *zip* compression (`unzip` command on remote)

`tar` : Use *tar gz* compression (`tar` command on remote)

Default : `tar`
```

The archive has a `.tar.gz` extension but it is not actually compressed.

I think the problem is at https://github.com/la-haute-societe/ssh-deploy-release/blob/master/src/Archiver.js#L33.

The archiver option is always an empty object.

I'm guessing there were some plans to wire in the gzip option specified here: https://github.com/la-haute-societe/ssh-deploy-release/blob/master/src/Options.js#L22

**Comment by nstCactus** [comment]
Good catch! I just pushed a new version of the NPM package to fix this.

Thanks!
