### ISSUE TITLE
Can't exclude a directory

### ISSUE THREAD

**Issue by pom421** [la-haute-societe/ssh-deploy-release#3]
Is it possible to make option.exclude work? 

This is what I have done : 

```
const Deployer = require('ssh-deploy-release');

const options = {
   localPath: '/Users/joe/workspace/codex/',
   host: 'my-server',
   port: '9222',
   username: 'joe',
   password: 'joe*',
   deployPath: '/var/lib/codex/',
   currentReleaseLink: 'htdocs',
   exclude : ['/.svn']
};

const deployer = new Deployer(options);
deployer.deployRelease(() => {
   console.log('Ok !')
});
```

There is a directory located in /Users/joe/workspace/codex/.svn.
I don't want this directory to be in my release. 
Unfortunately, the configuration doesn't work.

**Comment by maxime-colin** [comment]
`exclude` paths must be relative to the `localPath`.

I think it would work if you remove the first "/", like this :

````js
const options = {
   localPath: '/Users/joe/workspace/codex/',
   host: 'my-server',
   port: '9222',
   username: 'joe',
   password: 'joe*',
   deployPath: '/var/lib/codex/',
   currentReleaseLink: 'htdocs',
   exclude : ['.svn']
};
````

**Comment by pom421** [comment]
Unfortunately, it doesn't work, the .svn is still copied.

**Comment by pom421** [comment]
It works ! Thanks Maxime!

**Comment by maxime-colin** [comment]
👍 I updated the readme to clarify this point : https://github.com/la-haute-societe/ssh-deploy-release#optionsexclude
