### ISSUE TITLE
Releases are not removed

### ISSUE THREAD

**Issue by pom421** [la-haute-societe/ssh-deploy-release#5]
Hello,

The option releasesToKeep seems not to be seen by the tool. 

```
const Deployer = require('ssh-deploy-release');

const options = {
   localPath: '/Users/joe/codex/',
   host: 'joe.com',
   port: '9222',
   username: 'joe',
   password: 'mypwd',
   allowRemove: true,
   releasesToKeep: 5,
   deployPath: '/var/lib/www/codex/',
   currentReleaseLink: 'htdocs',
   exclude : ['.svn/**']
};

const deployer = new Deployer(options);
deployer.deployRelease(() => {
   console.log('Ok !')
});
```

The releases are well deployed but none of the releases are removed ever.

Do I need to use removeRelease explicitly? In that case, what is the purpose of allowRemove and releasesToKeep ?

**Comment by maxime-colin** [comment]
Hello,

Could you please try to deploy with the `debug` options (https://github.com/la-haute-societe/ssh-deploy-release#optionsdebug) ? it will display all commands executed on the remote server.

Find the command that deletes old releases, something like this : 
```
cd yourFolder
rm -rf `ls -r ...... | awk 'NR>.... 
```
And try this command directly on SSH (make sure you execute the command in the right folder), and maybe you will see some errors (file access rights issue, ... ?)

`AllowRemove` allows to delete all the remote releases with the `removeRelease` method (https://github.com/la-haute-societe/ssh-deploy-release#remove-release). it's useful to completely remove an environment, not to remove old releases on one environement.
